
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx_img
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress_img
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb_img
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_name
      - db_user
      - db_password
      - db_root_password
    env_file:
      - .env
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/miguel/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/miguel/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/db_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin:
    file: ../secrets/wp_admin.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user:
    file: ../secrets/wp_user.txt